---
kind: pipeline
type: docker
name: prod

steps:
  # 1) Tests + SonarQube backend
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      SONAR_HOST_URL:
        from_secret: sonar_host_url
    commands:
      - cd backend
      - mvn -DskipTests=false \
           -Dsonar.login=$SONAR_TOKEN \
           -Dsonar.host.url=$SONAR_HOST_URL \
           -Dsonar.qualitygate.wait=true \
           clean verify sonar:sonar
    when:
      event:
        - push
        - pull_request

  # 2) Tests frontend (Vitest)
  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      # Vitest sin --ci porque tu versión no lo soporta
      - npm test -- --run --watch=false
    when:
      event:
        - push
        - pull_request

  # 3) Build imágenes PROD (solo push a main)
  - name: build-images-prod
    image: docker:26-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker version
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend
    when:
      branch:
        - main
      event:
        - push

  # 4) Deploy PROD (solo push a main)
  - name: deploy-prod
    image: docker:26-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true

      - docker run -d --name backend-prod \
          -p 8083:8080 \
          aerolineas-backend-prod

      - docker run -d --name frontend-prod \
          -p 8086:80 \
          aerolineas-frontend-prod
    when:
      branch:
        - main
      event:
        - push

# Volumen para compartir el Docker del host con los steps
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
