---
kind: pipeline
type: docker
name: prod

steps:
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      SONAR_HOST_URL:
        from_secret: sonar_host_url
    commands:
      - cd backend
      # Tests backend
      - mvn -B clean verify -DskipTests=false
      # Análisis Sonar + Quality Gate
      - mvn -B sonar:sonar \
          -DskipTests=false \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.qualitygate.wait=true
    when:
      branch:
        - main          # prod = main
      event:
        - push
        - pull_request  # también en PR

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm test -- --watch=false
    when:
      branch:
        - main
      event:
        - push
        - pull_request

  - name: build-images-prod
    image: docker:26-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend
    when:
      branch:
        - main
      event:
        - push   # solo en push a main (después del merge)

  - name: deploy-prod
    image: docker:26-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true
      # OJO: aquí sin backslashes, todo en una sola línea
      - docker run -d --name backend-prod -p 8083:8080 aerolineas-backend-prod
      - docker run -d --name frontend-prod -p 8086:80 aerolineas-frontend-prod
    when:
      branch:
        - main
      event:
        - push   # deploy solo cuando ya hubo merge a main

services:
  - name: docker
    image: docker:26-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""   # importante para usar tcp://docker:2375

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
