  - name: backend-tests-and-sonar-uat
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      SONAR_HOST_URL:
        from_secret: sonar_host_url
    commands:
      - cd backend
      - mvn -B -DskipTests=false clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true
    when:
      branch:
        - uat
      event:
        - push
        - pull_request
