---
kind: pipeline
type: docker
name: ci-pr-prod

steps:
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_Token
      SONAR_HOST_URL:
        from_secret: sonar_host_URL
    commands:
      - cd backend
      - mvn -B clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - npm test -- --watch=false
    depends_on:
      - backend-tests-and-sonar

trigger:
  event:
    - pull_request
  branch:
    - main

---
kind: pipeline
type: docker
name: notify-ci-pr-prod-failure
depends_on:
  - ci-pr-prod

steps:
  - name: email
    image: plugins/email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from:
        from_secret: mail_from
      recipients:
        - dnatareno@unis.edu.gt
        - msblanco@unis.edu.gt
        - kdieguez@unis.edu.gt
     
      subject: "[DRONE] Fall贸 CI: ${DRONE_REPO} (${DRONE_BRANCH})"
      body: |
        Fall贸 el pipeline: ${DRONE_STAGE_NAME}
        Repo: ${DRONE_REPO}
        Branch: ${DRONE_BRANCH}
        Evento: ${DRONE_BUILD_EVENT}
        Commit: ${DRONE_COMMIT_SHA}
        Autor: ${DRONE_COMMIT_AUTHOR}
        Mensaje: ${DRONE_COMMIT_MESSAGE}

        Link del build:
        ${DRONE_BUILD_LINK}

trigger:
  event:
    - pull_request
  branch:
    - main
  status:
    - failure


---
kind: pipeline
type: docker
name: cd-prod

steps:
  - name: build-images-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend

  - name: deploy-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true
      - docker run -d --name backend-prod -p 8083:8080 aerolineas-backend-prod
      - docker run -d --name frontend-prod -p 8086:80 aerolineas-frontend-prod
    depends_on:
      - build-images-prod

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    - main

---
kind: pipeline
type: docker
name: notify-cd-prod-failure
depends_on:
  - cd-prod

steps:
  - name: email
    image: plugins/email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from:
        from_secret: mail_from
      recipients:
        - dnatareno@unis.edu.gt
        - msblanco@unis.edu.gt
        - kdieguez@unis.edu.gt
      
      subject: "[DRONE] Fall贸 CD/Deploy: ${DRONE_REPO} (${DRONE_BRANCH})"
      body: |
        Fall贸 el pipeline: ${DRONE_STAGE_NAME}
        Repo: ${DRONE_REPO}
        Branch: ${DRONE_BRANCH}
        Evento: ${DRONE_BUILD_EVENT}
        Commit: ${DRONE_COMMIT_SHA}

        Link del build:
        ${DRONE_BUILD_LINK}

trigger:
  event:
    - push
  branch:
    - main
  status:
    - failure
