---
kind: pipeline
type: docker
name: ci-pr-uat

steps:
  - name: backend-tests-sonar-qg
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_Token
      SONAR_HOST_URL:
        from_secret: sonar_host_URL
    commands:
      - cd backend
      - mvn -B clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm test -- --watch=false
    depends_on:
      - backend-tests-sonar-qg

trigger:
  event:
    - pull_request
  branch:
    - uat

---
kind: pipeline
type: docker
name: cd-uat

steps:
  - name: build-images-uat
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-uat ./backend
      - docker build -t aerolineas-frontend-uat ./frontend

  - name: deploy-uat
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-uat frontend-uat || true
      - docker rm backend-uat frontend-uat || true
      - docker run -d --name backend-uat -p 8082:8080 aerolineas-backend-uat
      - docker run -d --name frontend-uat -p 8085:80 aerolineas-frontend-uat
    depends_on:
      - build-images-uat

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    - uat
