---
kind: pipeline
type: docker
name: ci-pr-dev

steps:
  - name: backend-tests-sonar-qg
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_Token
      SONAR_HOST_URL:
        from_secret: sonar_host_URL
    commands:
      - cd backend
      - mvn -B clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - npm test -- --watch=false
    depends_on:
      - backend-tests-sonar-qg

  - name: notify-lead-ci-failure
    image: plugins/email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from:
        from_secret: mail_from
      recipients:
        - dnatareno@unis.edu.gt
        - msblanco@unis.edu.gt
        - kdieguez@unis.edu.gt
        
      subject: "[DRONE] Fall贸 CI: ${DRONE_REPO} (${DRONE_BRANCH})"
      body: |
        Fall贸 el pipeline: ${DRONE_STAGE_NAME}
        Repo: ${DRONE_REPO}
        Branch: ${DRONE_BRANCH}
        Evento: ${DRONE_BUILD_EVENT}
        Commit: ${DRONE_COMMIT_SHA}
        Autor: ${DRONE_COMMIT_AUTHOR}
        Mensaje: ${DRONE_COMMIT_MESSAGE}

        Link del build (ver el step en rojo):
        ${DRONE_BUILD_LINK}
    when:
      status:
        - failure
      event:
        - pull_request

trigger:
  event:
    - pull_request
  branch:
    - dev

---
kind: pipeline
type: docker
name: cd-dev

steps:
  - name: build-images-dev
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-dev ./backend
      - docker build -t aerolineas-frontend-dev ./frontend

  - name: deploy-dev
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-dev frontend-dev || true
      - docker rm backend-dev frontend-dev || true
      - docker run -d --name backend-dev --network ci-network -p 8081:8080 aerolineas-backend-dev
      - docker run -d --name frontend-dev -p 8084:80 aerolineas-frontend-dev
    depends_on:
      - build-images-dev

  - name: notify-lead-cd-failure
    image: plugins/email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from:
        from_secret: mail_from
      recipients:
        - dnatareno@unis.edu.gt
        - msblanco@unis.edu.gt
        - kdieguez@unis.edu.gt
      subject: "[DRONE] Fall贸 CD/Deploy: ${DRONE_REPO} (${DRONE_BRANCH})"
      body: |
        Fall贸 el pipeline: ${DRONE_STAGE_NAME}
        Repo: ${DRONE_REPO}
        Branch: ${DRONE_BRANCH}
        Evento: ${DRONE_BUILD_EVENT}
        Commit: ${DRONE_COMMIT_SHA}

        Link del build:
        ${DRONE_BUILD_LINK}
    when:
      status:
        - failure
      event:
        - push
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    - dev
