---
kind: pipeline
type: docker
name: ci-pr-prod

steps:
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_Token
      SONAR_HOST_URL:
        from_secret: sonar_host_URL
    commands:
      - cd backend
      - mvn -B clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm test -- --watch=false
    depends_on:
      - backend-tests-sonar-qg
trigger:
  event:
    - pull_request
  branch:
    - main

---
kind: pipeline
type: docker
name: cd-dev

steps:
  - name: build-images-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend

  - name: deploy-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true
      - docker run -d --name backend-prod -p 8083:8080 aerolineas-backend-prod
      - docker run -d --name frontend-prod -p 8086:80 aerolineas-frontend-prod
      depends_on:
      - build-images-dev

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    - main
