---
kind: pipeline
type: docker
name: prod

steps:
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      SONAR_HOST_URL:
        from_secret: sonar_host_url
    commands:
      - cd backend
      # Tests + Sonar + Quality Gate
      - mvn -B -DskipTests=false clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true
    when:
      branch:
        - main
      event:
        - push
        - pull_request

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm test -- --watch=false
    when:
      branch:
        - main
      event:
        - push
        - pull_request

  - name: build-images-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend
    when:
      branch:
        - main
      event:
        - push          # solo después del merge a main

  - name: deploy-prod
    image: docker:26-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true

      - docker run -d --name backend-prod -p 8083:8080 aerolineas-backend-prod
      - docker run -d --name frontend-prod -p 8086:80 aerolineas-frontend-prod
    when:
      branch:
        - main
      event:
        - push          # deploy solo en push a main

# Usamos el Docker del host (NO DIND)
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
