---
kind: pipeline
type: docker
name: prod

# Usar el Docker del host
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: backend-tests-and-sonar
    image: maven:3.9-eclipse-temurin-17
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
      SONAR_HOST_URL:
        from_secret: sonar_host_url
    commands:
      - cd backend
      - mvn clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true
    when:
      event:
        - push
        - pull_request

  - name: frontend-tests
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm test
    when:
      event:
        - push
        - pull_request

  - name: build-images-prod
    image: docker:26-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t aerolineas-backend-prod ./backend
      - docker build -t aerolineas-frontend-prod ./frontend
    when:
      event:
        - push   # solo cuando ya se hace push a main

  - name: deploy-prod
    image: docker:26-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop backend-prod frontend-prod || true
      - docker rm backend-prod frontend-prod || true
      - docker run -d --name backend-prod -p 8083:8080 aerolineas-backend-prod
      - docker run -d --name frontend-prod -p 8086:80 aerolineas-frontend-prod
    when:
      event:
        - push   # solo en push, no en pull_request

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
